using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClientMCR.CountryFormatAddress
{
    public class listOfCountries
    {
        List<country> countries;
        public listOfCountries()
        {
            countries = new List<country>();

            countries.Add(new country() { countryName = "Afghanistan" });
            countries.Add(new country() { countryName = "Albania" });
            countries.Add(new country() { countryName = "Algeria" });
            countries.Add(new country() { countryName = "Andorra" });
            countries.Add(new country() { countryName = "Angola" });
            countries.Add(new country() { countryName = "Antigua and Barbuda" });
            countries.Add(new country() { countryName = "Argentina" });
            countries.Add(new country() { countryName = "Armenia" });
            countries.Add(new country() { countryName = "Australia" });
            countries.Add(new country() { countryName = "Austria" });
            countries.Add(new country() { countryName = "Azerbaijan" });
            countries.Add(new country() { countryName = "Bahamas" });
            countries.Add(new country() { countryName = "Bahrain" });
            countries.Add(new country() { countryName = "Bangladesh" });
            countries.Add(new country() { countryName = "Barbados" });
            countries.Add(new country() { countryName = "Belarus" });
            countries.Add(new country() { countryName = "Belgium" });
            countries.Add(new country() { countryName = "Belize" });
            countries.Add(new country() { countryName = "Benin" });
            countries.Add(new country() { countryName = "Bhutan" });
            countries.Add(new country() { countryName = "Bolivia" });
            countries.Add(new country() { countryName = "Bosnia and Herzegovina" });
            countries.Add(new country() { countryName = "Botswana" });
            countries.Add(new country() { countryName = "Brazil" });
            countries.Add(new country() { countryName = "Brunei" });
            countries.Add(new country() { countryName = "Bulgaria" });
            countries.Add(new country() { countryName = "Burkina Faso" });
            countries.Add(new country() { countryName = "Burundi" });
            countries.Add(new country() { countryName = "Cote d'Ivoire" });
            countries.Add(new country() { countryName = "Cabo Verde" });
            countries.Add(new country() { countryName = "Cambodia" });
            countries.Add(new country() { countryName = "Cameroon" });
            countries.Add(new country() { countryName = "Canada" });
            countries.Add(new country() { countryName = "Central African Republic" });
            countries.Add(new country() { countryName = "Chad" });
            countries.Add(new country() { countryName = "Chile" });
            countries.Add(new country() { countryName = "China" });
            countries.Add(new country() { countryName = "Colombia" });
            countries.Add(new country() { countryName = "Comoros" });
            countries.Add(new country() { countryName = "Congo (Congo-Brazzaville)" });
            countries.Add(new country() { countryName = "Costa Rica" });
            countries.Add(new country() { countryName = "Croatia" });
            countries.Add(new country() { countryName = "Cuba" });
            countries.Add(new country() { countryName = "Cyprus" });
            countries.Add(new country() { countryName = "Czechia (Czech Republic)" });
            countries.Add(new country() { countryName = "Democratic Republic of the Congo" });
            countries.Add(new country() { countryName = "Denmark" });
            countries.Add(new country() { countryName = "Djibouti" });
            countries.Add(new country() { countryName = "Dominica" });
            countries.Add(new country() { countryName = "Dominican Republic" });
            countries.Add(new country() { countryName = "Ecuador" });
            countries.Add(new country() { countryName = "Egypt" });
            countries.Add(new country() { countryName = "El Salvador" });
            countries.Add(new country() { countryName = "Equatorial Guinea" });
            countries.Add(new country() { countryName = "Eritrea" });
            countries.Add(new country() { countryName = "Estonia" });
            countries.Add(new country() { countryName = "Eswatini (fmr. \"Swaziland\")" });
            countries.Add(new country() { countryName = "Ethiopia" });
            countries.Add(new country() { countryName = "Fiji" });
            countries.Add(new country() { countryName = "Finland" });
            countries.Add(new country() { countryName = "France" });
            countries.Add(new country() { countryName = "Gabon" });
            countries.Add(new country() { countryName = "Gambia" });
            countries.Add(new country() { countryName = "Georgia" });
            countries.Add(new country() { countryName = "Germany" });
            countries.Add(new country() { countryName = "Ghana" });
            countries.Add(new country() { countryName = "Greece" });
            countries.Add(new country() { countryName = "Grenada" });
            countries.Add(new country() { countryName = "Guatemala" });
            countries.Add(new country() { countryName = "Guinea" });
            countries.Add(new country() { countryName = "Guinea-Bissau" });
            countries.Add(new country() { countryName = "Guyana" });
            countries.Add(new country() { countryName = "Haiti" });
            countries.Add(new country() { countryName = "Holy See" });
            countries.Add(new country() { countryName = "Honduras" });
            countries.Add(new country() { countryName = "Hong Kong" });
            countries.Add(new country() { countryName = "Hungary" });
            countries.Add(new country() { countryName = "Iceland" });
            countries.Add(new country() { countryName = "India" });
            countries.Add(new country() { countryName = "Indonesia" });
            countries.Add(new country() { countryName = "Iran" });
            countries.Add(new country() { countryName = "Iraq" });
            countries.Add(new country() { countryName = "Ireland" });
            countries.Add(new country() { countryName = "Israel" });
            countries.Add(new country() { countryName = "Italy" });
            countries.Add(new country() { countryName = "Jamaica" });
            countries.Add(new country() { countryName = "Japan" });
            countries.Add(new country() { countryName = "Jordan" });
            countries.Add(new country() { countryName = "Kazakhstan" });
            countries.Add(new country() { countryName = "Kenya" });
            countries.Add(new country() { countryName = "Kiribati" });
            countries.Add(new country() { countryName = "Kuwait" });
            countries.Add(new country() { countryName = "Kyrgyzstan" });
            countries.Add(new country() { countryName = "Laos" });
            countries.Add(new country() { countryName = "Latvia" });
            countries.Add(new country() { countryName = "Lebanon" });
            countries.Add(new country() { countryName = "Lesotho" });
            countries.Add(new country() { countryName = "Liberia" });
            countries.Add(new country() { countryName = "Libya" });
            countries.Add(new country() { countryName = "Liechtenstein" });
            countries.Add(new country() { countryName = "Lithuania" });
            countries.Add(new country() { countryName = "Luxembourg" });
            countries.Add(new country() { countryName = "Macao" });
            countries.Add(new country() { countryName = "Madagascar" });
            countries.Add(new country() { countryName = "Malawi" });
            countries.Add(new country() { countryName = "Malaysia" });
            countries.Add(new country() { countryName = "Maldives" });
            countries.Add(new country() { countryName = "Mali" });
            countries.Add(new country() { countryName = "Malta" });
            countries.Add(new country() { countryName = "Marshall Islands" });
            countries.Add(new country() { countryName = "Mauritania" });
            countries.Add(new country() { countryName = "Mauritius" });
            countries.Add(new country() { countryName = "Mexico" });
            countries.Add(new country() { countryName = "Micronesia" });
            countries.Add(new country() { countryName = "Moldova" });
            countries.Add(new country() { countryName = "Monaco" });
            countries.Add(new country() { countryName = "Mongolia" });
            countries.Add(new country() { countryName = "Montenegro" });
            countries.Add(new country() { countryName = "Morocco" });
            countries.Add(new country() { countryName = "Mozambique" });
            countries.Add(new country() { countryName = "Myanmar (formerly Burma)" });
            countries.Add(new country() { countryName = "Namibia" });
            countries.Add(new country() { countryName = "Nauru" });
            countries.Add(new country() { countryName = "Nepal" });
            countries.Add(new country() { countryName = "Netherlands" });
            countries.Add(new country() { countryName = "New Zealand" });
            countries.Add(new country() { countryName = "Nicaragua" });
            countries.Add(new country() { countryName = "Niger" });
            countries.Add(new country() { countryName = "Nigeria" });
            countries.Add(new country() { countryName = "North Korea" });
            countries.Add(new country() { countryName = "North Macedonia" });
            countries.Add(new country() { countryName = "Norway" });
            countries.Add(new country() { countryName = "Oman" });
            countries.Add(new country() { countryName = "Pakistan" });
            countries.Add(new country() { countryName = "Palau" });
            countries.Add(new country() { countryName = "Palestine State" });
            countries.Add(new country() { countryName = "Panama" });
            countries.Add(new country() { countryName = "Papua New Guinea" });
            countries.Add(new country() { countryName = "Paraguay" });
            countries.Add(new country() { countryName = "Peru" });
            countries.Add(new country() { countryName = "Philippines" });
            countries.Add(new country() { countryName = "Poland" });
            countries.Add(new country() { countryName = "Portugal" });
            countries.Add(new country() { countryName = "Qatar" });
            countries.Add(new country() { countryName = "Romania" });
            countries.Add(new country() { countryName = "Russia" });
            countries.Add(new country() { countryName = "Rwanda" });
            countries.Add(new country() { countryName = "Saint Kitts and Nevis" });
            countries.Add(new country() { countryName = "Saint Lucia" });
            countries.Add(new country() { countryName = "Saint Vincent and the Grenadines" });
            countries.Add(new country() { countryName = "Samoa" });
            countries.Add(new country() { countryName = "San Marino" });
            countries.Add(new country() { countryName = "Sao Tome and Principe" });
            countries.Add(new country() { countryName = "Saudi Arabia" });
            countries.Add(new country() { countryName = "Senegal" });
            countries.Add(new country() { countryName = "Serbia" });
            countries.Add(new country() { countryName = "Seychelles" });
            countries.Add(new country() { countryName = "Sierra Leone" });
            countries.Add(new country() { countryName = "Singapore" });
            countries.Add(new country() { countryName = "Slovakia" });
            countries.Add(new country() { countryName = "Slovenia" });
            countries.Add(new country() { countryName = "Solomon Islands" });
            countries.Add(new country() { countryName = "Somalia" });
            countries.Add(new country() { countryName = "South Africa" });
            countries.Add(new country() { countryName = "South Korea" });
            countries.Add(new country() { countryName = "South Sudan" });
            countries.Add(new country() { countryName = "Spain" });
            countries.Add(new country() { countryName = "Sri Lanka" });
            countries.Add(new country() { countryName = "Sudan" });
            countries.Add(new country() { countryName = "Suriname" });
            countries.Add(new country() { countryName = "Sweden" });
            countries.Add(new country() { countryName = "Switzerland" });
            countries.Add(new country() { countryName = "Syria" });
            countries.Add(new country() { countryName = "Taiwan" });
            countries.Add(new country() { countryName = "Tajikistan" });
            countries.Add(new country() { countryName = "Tanzania" });
            countries.Add(new country() { countryName = "Thailand" });
            countries.Add(new country() { countryName = "Timor-Leste" });
            countries.Add(new country() { countryName = "Togo" });
            countries.Add(new country() { countryName = "Tonga" });
            countries.Add(new country() { countryName = "Trinidad and Tobago" });
            countries.Add(new country() { countryName = "Tunisia" });
            countries.Add(new country() { countryName = "Turkey" });
            countries.Add(new country() { countryName = "Turkmenistan" });
            countries.Add(new country() { countryName = "Tuvalu" });
            countries.Add(new country() { countryName = "Uganda" });
            countries.Add(new country() { countryName = "Ukraine" });
            countries.Add(new country() { countryName = "United Arab Emirates" });
            countries.Add(new country() { countryName = "United Kingdom" });
            countries.Add(new country() { countryName = "United States of America" });
            countries.Add(new country() { countryName = "Uruguay" });
            countries.Add(new country() { countryName = "Uzbekistan" });
            countries.Add(new country() { countryName = "Vanuatu" });
            countries.Add(new country() { countryName = "Venezuela" });
            countries.Add(new country() { countryName = "Vietnam" });
            countries.Add(new country() { countryName = "Yemen" });
            countries.Add(new country() { countryName = "Zambia" });
            countries.Add(new country() { countryName = "Zimbabwe" });
        }

        public List<country> GetCountries()
        {
            return countries;
        }
        
    }
}
